### ISSUE TITLE
not able to redirect.

### ISSUE THREAD

**Issue by shivi74** [brutasse/django-password-reset#29]
After entering the email on '/password_reset/recover/', it is not redirected. Instead same recovery page is shown!

**Comment by brutasse** [comment]
There's probably a form error then. Are you displaying them on the recovery page?

**Comment by shivi74** [comment]
i am just displaying a simple template on '/password_reset/recover/' url.

**Comment by VitorEulalioReis** [comment]
Same problem here, any workaround?

**Comment by shivi74** [comment]
Yea! There are templates in packages of password_reset on the path something like : "~/venv/local/lib/python2.7/site-packages/password_reset/templates/"

To solve this either add this path to TEMPLATE_DIRS or copy the password_reset directory for templates under your specified template directory.
