### ISSUE TITLE
loads_with_timestamp

### ISSUE THREAD

**Issue by beshrkayali** [brutasse/django-password-reset#37]
Hi guys,

I was debugging some issues I'm having with `django-password-reset` and noticed that the `RecoverDone` view makes a call to `loads_with_timestamp` function defined right above it: https://github.com/brutasse/django-password-reset/blob/0.7/password_reset/views.py#L24

The docstring states that the function should return the unsigned value along with its timestamp, but there's a try/except in case `signing.SignatureExpired` exception doesn't occur, `None` would be returned which means that the view will fail returning a `TypeError` exception because it would be trying to iterate over `None` to assign `timestamp` and `email` in the context.

Thought that there might be some inconsistency there.

**Comment by brutasse** [comment]
The exception is always supposed to occur: `max_age=-1` requires the string to be signed in the future, which never happens unless you have a distributed setup with badly synchronized clocks and then you're in for lots of other surprises :)

Did you actually see an occurrence of this function returning `None`? I could add an `else` clause to the `try` block but it really doesn't seem to be necessary.

**Comment by beshrkayali** [comment]
Aha! I did not notice that `max_age=-1` :) Had a few seconds difference on a couple of newly spun ec2s and that was indeed the problem. Thanks!
