### ISSUE TITLE
Django 4.0 Url Problem

### ISSUE THREAD

**Issue by Voxmundi** [brutasse/django-password-reset#85]
from django.conf.urls import url (deprecated in Django 4.0)
I use re_path the urls to solve this
But also it throw an error on:  from django.utils.translation import gettext_lazy as _
ugettext_lazy (has been removed in Django 4.0)
use : from django.utils.translation import gettext_lazy as _
When you done this its giving an error:
 user_recovers_password = Signal(
TypeError: __init__() got an unexpected keyword argument 'providing_args'

**Comment by Voxmundi** [comment]
When you edit Signal file such as 
user_recovers_password = Signal('request')
seems working.

**Comment by claresloggett** [comment]
Looks like someone had submitted a relevant PR: https://github.com/brutasse/django-password-reset/pull/84 

It's been open since 2021 however
